- alias: Weather Forecast
  trigger:
    platform: time
    at: 08:30:00
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: "{% set hour = now().strftime(\"%H\") %} {% set weekday_full_name =\
        \ now().strftime(\"%A\") %} {% set month_full_name = now().strftime(\"%B\"\
        ) %} {% set year_with_century = now().strftime(\"%Y\") %} {% set day = now().strftime(\"\
        %-d\") %} {% set weekday = now().strftime(\"%w\") %} Good {% if now().strftime(\"\
        %H\")|int < 12 %} morning  {% elif now().strftime(\"%H\")|int < 18 %} afternoon\
        \ {% else %} evening {% endif %} everyone.  Todays date is {{ weekday_full_name\
        \ }} {{ month_full_name }} the\n    {% if day | int == 1 or day | int == 21\
        \ or day | int == 31 %}\n      {{ day }}st\n    {% elif day | int == 2 or\
        \ day | int == 22 %}\n      {{ day }}nd\n    {% elif day | int == 3 or day\
        \ | int == 23 %}\n      {{ day }}rd\n    {% else %}\n      {{ day }}th\n \
        \   {% endif %}.\n{{ year_with_century }}. Todays Daily Announcements.  {%\
        \ if states('sensor.christmas_day') | float < 60 %} There are {{ states.sensor.christmas_day.state\
        \ | int - 1 }} more sleeps to Christmas. {%endif %}  The house internal temperature\
        \ is {{  states.climate.heating.attributes.current_temperature | replace(\"\
        .\",\" point \") }} degrees celsius. The thermostat is set to {{  states.climate.heating.attributes.temperature\
        \ | replace(\".\",\" point \") }} degrees celcius. It's currently {{states.sensor.dark_sky_summary.state}}\
        \ and {{states.sensor.dark_sky_temperature.state|round}} degrees in Childwall.\
        \  Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(\"\
        .\", \"\")}}, with a high of {{states.sensor.dark_sky_daytime_high_temperature.state|round}}\
        \ degrees,  and a low of {{states.sensor.dark_sky_overnight_low_temperature.state|round}}\
        \ degrees. End of Announcements, have a nice day!\n"
  id: 80d435c19d70418b95e3f07130c65147
- alias: Home Greeting Luke
  trigger:
    platform: state
    entity_id: device_tracker.58e28f6772fe
    from: not_home
    to: home
  condition:
    condition: time
    after: '15:00:00'
    before: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: notify.ruth
    data_template:
      title: Home Alert!
      message: Luke has arrived Home
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Luke has arrived Home
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: Welcome Home Luke, hope you had a great day at school!
  id: bdafbbc66f41401d99c0218d3d7a97e1
- alias: Home Greeting Luke via ps4 use
  trigger:
    platform: numeric_state
    entity_id: sensor.ps4_today
    value_template: '{{ states.sensor.ps4_today.state }}'
    above: 0
  condition:
    condition: and
    conditions:
    - condition: time
      after: '15:00:00'
      before: '17:00:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.58e28f6772fe
      state: not_home
  action:
  - service: notify.ruth
    data_template:
      title: Home Alert!
      message: Luke has arrived Home
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Luke has arrived Home
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.kitchen
    data_template:
      message: Welcome Home Luke, hope you had a great day at school!
  id: 466e25af68e24b9fb50177fd762587e1
- alias: Luke Leave
  trigger:
    platform: state
    entity_id: device_tracker.58e28f6772fe
    from: home
    to: not_home
  action:
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Luke has gone out
  id: 823dc4806423463f957e0be4f22b039d
- id: '1538941282605'
  alias: Refresh Birthday Sensors
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - service: python_script.birthdays
- alias: Home Greeting Zak
  trigger:
    platform: state
    entity_id: device_tracker.zak_pc
    from: not_home
    to: home
  condition:
    condition: time
    after: '15:00:00'
    before: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Zak has arrived Home
  - service: notify.ruth
    data_template:
      title: Home Alert!
      message: Zak has arrived Home
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: Welcome Home Zak, hope you had a great day at school!
  id: b1da6243437041e685bde7bbb2de53af
- id: '1539030610493'
  alias: 5 Min Game Warning
  trigger:
  - at: '19:55'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The time is 19:55, Luke & Zak, you have 5 minutes to finish your games
- alias: Game Over
  trigger:
  - at: '20:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The time is 8 Oclock, time to turn off all electronics.  The playstation
        has been on for {{states.sensor.ps4_today.state|round}} hours today.
  id: d0e63fa7400c498c857966da6d157931
- alias: School Time
  trigger:
  - at: 08:45
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The time is 08:45, Zak, time to leave for school, have a great day!
  id: 32627922fe1245609515b2488f2644f2
- id: '1539075329069'
  alias: Playstation Time Limit
  trigger:
    platform: numeric_state
    entity_id: sensor.ps4_today
    value_template: '{{ states.sensor.ps4_today.state }}'
    above: 5
  condition:
    condition: time
    after: '19:00:00'
    before: '21:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The playstation has been on for more than 4 hours, please finish your
        game and turn it off.
- id: 07ac09c8b3d64dbd813cc63e9038649a
  alias: Aquarium Light On
  trigger:
  - at: '18:00:00'
    platform: time
  action:
  - data_template:
      message: Turning Aquarium Light on
    entity_id: media_player.downstairs
    service: tts.google_say
  - delay: 00:00:02
  - entity_id: switch.aquarium_light
    service: switch.turn_on
- alias: Aquarium Light Off
  trigger:
    platform: time
    at: '21:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.aquarium_light
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.aquarium_light
  id: 338a5aedb5024f228a66a258cb35cd93
- alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    service: ifttt.trigger
    data:
      event: Home Alert!
      value1: Home Assistant has restarted!
  id: 65843367a4dd45cb8870252f43e3f845
- alias: Dusk Lights on
  trigger:
    platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: Turning Lights on at dusk
  - delay: 00:00:02
  - service: switch.turn_on
    entity_id: switch.toy_room_light
  - delay: 00:00:02
  - service: switch.turn_on
    entity_id: switch.living_room_light
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Dusk lights activated
  id: 9befa5e676394e4286ed9c44d0159e88
- alias: Bedtime Lights Off Weekday
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.toy_room_light
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.living_room_light
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.toy_room_light
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.living_room_light
  id: 8cf26a22df39486f97c5c9be129e7a92
- alias: Bedtime Lights Off Weekend
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    condition: time
    weekday:
    - fri
    - sat
  action:
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.toy_room_light
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.living_room_light
  id: 1fadcb826b044baebda6d4bec347ab6b
- alias: IFTTT WebHook Received
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
  id: db17a12ec1d642f39024ad097d69e85f
- id: '1540578279862'
  alias: Hive OverTemp
  trigger:
  - above: '23'
    entity_id: sensor.hall_thermostat_temp_setting
    platform: numeric_state
  condition: []
  action:
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: Hall thermostat set to {{ states.climate.heating.attributes.temperature
        }} resetting to MAX:23
  - service: climate.set_temperature
    data:
      entity_id: climate.heating
      temperature: 23
- id: '1540642637828'
  alias: Aquarium Temp Low
  trigger:
  - above: '0'
    below: '24'
    entity_id: sensor.aquarium_temperature
    platform: numeric_state
  condition: []
  action:
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The Aquarium Temperature is currently too low at {{ states.sensor.aquarium_temperature.state
        }} degrees.
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: The Aquarium Temperature is currently too low at {{ states.sensor.aquarium_temperature.state
        }} degrees.
- id: '1540642647828'
  alias: Aquarium Temp High
  trigger:
  - above: '26'
    below: '99'
    entity_id: sensor.aquarium_temperature
    platform: numeric_state
  condition: []
  action:
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The Aquarium Temperature is currently too high at {{ states.sensor.aquarium_temperature.state
        }} degrees.
  - service: notify.barry
    data_template:
      title: Home Alert!
      message: The Aquarium Temperature is currently too high at {{ states.sensor.aquarium_temperature.state
        }} degrees.
- alias: Test Christmas
  trigger:
    platform: time
    at: 08:31:00
  action:
  - service: tts.google_say
    entity_id: media_player.computer_room
    data_template:
      message: '{% if states(''sensor.christmas_day'') | float < 60 %} There are {{
        states.sensor.christmas_day.state }} more sleeps to Christmas. {%endif %}'
  id: a31777a54e274a76a9174a8eda380692
- id: '1541363072998'
  alias: Alarm Beep On Arm
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    from: disarmed
    platform: state
    to: armed_home
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.beep_beep
    service: switch.turn_on
- id: '1541463072998'
  alias: Alarm Beep On Disarm
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    from: armed_home
    platform: state
    to: disarmed
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.chime
    service: switch.turn_on
- id: '1541363860629'
  alias: door chime
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.chime
    service: switch.turn_on
- id: '1542135100403'
  alias: Hive Hub Offline
  trigger:
  - entity_id: sensor.hive_hub_status
    from: Online
    platform: state
    to: Offline
  condition: []
  action:
  - data_template:
      message: Hive Hub has gone offline
    entity_id: media_player.downstairs
    service: tts.google_say
  - data_template:
      message: Hive Hub has gone offline
      title: Home Alert!
    service: notify.barry
- id: '1542135100409'
  alias: Hive Hub Online
  trigger:
  - entity_id: sensor.hive_hub_status
    from: Offline
    platform: state
    to: Online
  condition: []
  action:
  - data_template:
      message: Hive Hub has come back online
    entity_id: media_player.downstairs
    service: tts.google_say
  - data_template:
      message: Hive Hub has come back online
      title: Home Alert!
    service: notify.barry
