homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.395311
  longitude: -2.885974
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 52
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

recorder:
  db_url: !secret recorder_db_url

logger:
  default: info
  logs:
    homeassistant.components.sensor.hive: debug
    homeassistant.components.konnected: debug

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
#  api_password: !secret http_api_password
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Notifications
notify:
  - name: barry
    platform: command_line
    command: 'read input ; /usr/bin/curl -u o.8gaDPBoKPS7G8KcFopIoxoB1Uk2z42Uz https://api.pushbullet.com/v2/pushes -d type=note -d title="Home Alert!" -d "body=${input}"'
  - name: ruth
    platform: pushbullet
    api_key: !secret pushbullet_api_ruth

panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://192.168.0.67:1880
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://192.168.0.67:8888/
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.0.67:3000

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state


alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1234
    pending_time: 5
    delay_time: 5
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

# Webcams
#camera:
#- platform: mjpeg
#  mjpeg_url: http://192.168.0.65/html/cam_pic_new.php?pDelay=400000
#  name: AquaCam

ffmpeg:

camera:
  - platform: generic
    name: Fish Cam
    still_image_url: http://192.168.0.65/html/cam_pic.php
  - platform: yi
    name: Computer Room
    host: '192.168.0.231'
    password: !secret yi
  - platform: yi
    name: Living Room
    host: '192.168.0.232'
    password: !secret yi    
  - platform: yi
    name: Kitchen
    host: '192.168.0.218'
    password: !secret yi

ifttt:
  key: !secret ifttt

weather:
  - platform: darksky
    api_key: !secret darksky_api2

# Weather prediction
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'

  - platform: yr
  - platform: command_line
    name: Aquarium Temperature
    command: "curl --silent -X GET http://192.168.0.65/html/28-041685bc33ff_temp.txt"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
  - platform: command_line
    name: Aquarium Temperature 2
    command: "curl --silent -X GET http://192.168.0.65/html/28-020791776b6b_temp.txt"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
  - platform: command_line
    name: Garage Temperature
    command: "curl --silent -X GET http://192.168.0.63/1-wire/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
  - platform: command_line
    name: Hot Water Temperature
    command: "curl --silent -X GET http://192.168.0.63/1-wire/temp2"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
  - platform: season
    type: astronomical
  - platform: uptime
  - platform: version
  - platform: rest
    resource: http://192.168.0.170:15619/status
    name: konnected 1 wifi
    value_template: '{{ value_json.rssi }}'
  - platform: rest
    resource: http://192.168.0.171:15271/status
    name: konnected 2 wifi
    value_template: '{{ value_json.rssi }}'
  - platform: rest
    resource: http://192.168.0.172:8101/status
    name: konnected 3 wifi
    value_template: '{{ value_json.rssi }}'
  - platform: rest
    resource: http://192.168.0.173:19754/status
    name: konnected 4 wifi
    value_template: '{{ value_json.rssi }}'

#  - platform: template
#    sensors:
#      playstation:
#        value_template: "{% if is_state('device_tracker.0cfe45d692b7', 'home') %}ON{% else %}OFF{% endif %}"
#        friendly_name: 'Playstation 4'
#      280dfc4c0320:
#        value_template: "{% if is_state('device_tracker.280dfc4c0320', 'home') %}ON{% else %}OFF{% endif %}"

  - platform: darksky
    api_key: !secret darksky_api3
    update_interval: '00:30'
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase

  - platform: history_stats
    name: PS4 today
    entity_id: switch.ps4
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'


  - platform: template
    sensors:
      ps4_today_time:
        value_template: '{{ states.sensor.ps4_today.attributes.value }}'
  - platform: template
    sensors:
      konnected_1_wifi_strength:
        value_template: '{{ (((( states.sensor.konnected_1_wifi.state | float + 100 ) | float * 2 ), 100 )) |min }}'
  - platform: template
    sensors:
      konnected_2_wifi_strength:
        value_template: '{{ (((( states.sensor.konnected_2_wifi.state | float + 100 ) | float * 2 ), 100 )) |min }}'
  - platform: template
    sensors:
      konnected_3_wifi_strength:
        value_template: '{{ (((( states.sensor.konnected_3_wifi.state | float + 100 ) | float * 2 ), 100 )) |min }}'
  - platform: template
    sensors:
      konnected_4_wifi_strength:
        value_template: '{{ (((( states.sensor.konnected_4_wifi.state | float + 100 ) | float * 2 ), 100 )) |min }}'

  - platform: template
    sensors:
      konnected_1:
        value_template: "{% if is_state('device_tracker.konnected1', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      konnected_2:
        value_template: "{% if is_state('device_tracker.konnected2', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      konnected_3:
        value_template: "{% if is_state('device_tracker.konnected3', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      konnected_4:
        value_template: "{% if is_state('device_tracker.konnected4', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      sonoff_150:
        value_template: "{% if is_state('device_tracker.sonoff150', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      sonoff_151:
        value_template: "{% if is_state('device_tracker.sonoff151', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      sonoff_152:
        value_template: "{% if is_state('device_tracker.sonoff152', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      nas_1:
        value_template: "{% if is_state('device_tracker.nas', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      aqua_1:
        value_template: "{% if is_state('device_tracker.aqua', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"
      izzy_1:
        value_template: "{% if is_state('device_tracker.izzy', 'home') %}ONLINE{% else %}OFFLINE{% endif %}"

  - platform: template
    sensors:
       hall_temperature:
          friendly_name: "Hall Temperature"
          value_template: "{{  states.climate.heating.attributes.current_temperature }}"
          unit_of_measurement: "°C"

  - platform: template
    sensors:
       hive_battery:
          friendly_name: "Hive Battery"
          value_template: "{{  states.climate.heating.attributes.battery_level }}"

  - platform: template
    sensors:
       hall_thermostat_temp_setting:
          friendly_name: "Hall Thermostat Temp Setting"
          value_template: "{{  states.climate.heating.attributes.temperature }}"

  - platform: template
    sensors:
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'

binary_sensor:
  - platform: template
    sensors:
      study_movement:
        friendly_name: Study Movement
        value_template: '{{(as_timestamp(now()) - as_timestamp(states.binary_sensor.study.last_changed) < 1800)}}'
        device_class: motion
        entity_id: sensor.time

  - platform: mqtt
    state_topic: "tele/sonoff151/RESULT"
    name: 'Office Motion'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: 'D19A0E'
    payload_off: 'D19A0Eoff'
    device_class: motion
#    optimistic: false
    qos: 1
#    remain: false

  - platform: mqtt
    state_topic: "tele/sonoff151/RESULT"
    name: 'Front Door'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '14A70A'
    payload_off: '14A70E'
    device_class: door

  - platform: mqtt
    state_topic: "tele/sonoff151/RESULT"
    name: 'Garage Door'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '168C0A'
    payload_off: '168C0E'
    device_class: door

#  - platform: uk_transport
#    app_id: !secret uk_transport_appid
#    app_key: !secret uk_transport_appkey
#    queries:
#      - mode: train
#        origin: BGE
#        destination: LIV
#  - platform: template
#    sensors:
#      kitchen_state:
#        value_template: '{{ states("media_player.kitchen") }}'
#        friendly_name: 'Kitchen Chromecast'



# Text to speech
tts:
  - platform: google

# Cloud
cloud:

input_select:
  exterior_light_type:
    name: Exterior Lights Settings
    options:
     - "White"
     - "Red"
     - "Blue"
     - "Green"
     - "Flash"
     - "Strobe"
     - "Fade"
     - "Smooth"
    initial: White
    icon: mdi:lightbulb-on-online

mqtt:
  broker: 192.168.0.63
  discovery: true
  discovery_prefix: homeassistant

light:
  - platform: mqtt
    schema: json
    name: "LivingRoomLED"
    state_topic: "home/LivingRoomLED_ha/state/out"
    command_topic: "home/LivingRoomLED_ha/state/in"
#    on_command_type: 'first'
    effect: true
    effect_list:
    ######
      - "Static"
      - "Blink"
      - "Breath"
      - "Color Wipe"
      - "Color Wipe Inverse"
      - "Color Wipe Reverse"
      - "Color Wipe Reverse Inverse"
      - "Color Wipe Random"
      - "Random Color"
      - "Single Dynamic"
      - "Multi Dynamic"
      - "Rainbow"
      - "Rainbow Cycle"
      - "Scan"
      - "Dual Scan"
      - "Fade"
      - "Theater Chase"
      - "Theater Chase Rainbow"
      - "Running Lights"
      - "Twinkle"
      - "Twinkle Random"
      - "Twinkle Fade"
      - "Twinkle Fade Random"
      - "Sparkle"
      - "Flash Sparkle"
      - "Hyper Sparkle"
      - "Strobe"
      - "Strobe Rainbow"
      - "Multi Strobe"
      - "Blink Rainbow"
      - "Chase White"
      - "Chase Color"
      - "Chase Random"
      - "Chase Rainbow"
      - "Chase Flash"
      - "Chase Flash Random"
      - "Chase Rainbow White"
      - "Chase Blackout"
      - "Chase Blackout Rainbow"
      - "Color Sweep Random"
      - "Running Color"
      - "Running Red Blue"
      - "Running Random"
      - "Larson Scanner"
      - "Comet"
      - "Fireworks"
      - "Fireworks Random"
      - "Merry Christmas"
      - "Fire Flicker"
      - "Fire Flicker (soft)"
      - "Fire Flicker (intense)"
      - "Circus Combustus"
      - "Halloween"
      - "Bicolor Chase"
      - "Tricolor Chase"
      - "ICU"
      - "E131"
    brightness: true
    color_temp: true
    rgb: true
    optimistic: false
    qos: 0
    retain: true
    
input_number:
  neopixel_animation_speed:
    name: NeoPixel Animation Speed
    initial: 200
    min: 0
    max: 255
    step: 5

person:
  - name: Bazza
    id: baz
    device_trackers:
      - device_tracker.8c4500aad0bf
  

switch:
  - platform: broadlink
    host: 192.168.0.180
    mac: 78:0F:77:47:89:80
    type: rm_mini
    switches:
      exterior_lights:
        friendly_name: "Exterior Lights"
        command_on: "JgBYAAABKpQVERAUFBEVERAUFBEVERAVFDUROBI5FDURFBQ2ETgVNhQ1ETkUEREUFBEVEBEUFBEVEBEUFDYROBU2FDUROBI5FAAFOgABLUcSAAxEAAEtRxEADQU="
        command_off: "JgCQAAABKZQUEhMRFREQFhMQFRERFBQQFTYUNRE5FDYUERQ2FDUSOBUQETkRFBEUFBEUEREUFBEVNRQRETkUNRE5FTUUNhM2FQAFOgABKksUAAxCAAEpSxQADEIAASpLEwAMQQABLUkTAAxDAAEqSxQADEIAAStJEwAMQwABKksSAAxEAAEsSRIADEMAASpJFQANBQAAAAAAAAAA"
  - platform: command_line
    switches:
      # toy_room_light:
      #   command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey2"
      #   command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey10"
      #   friendly_name: 'Toy Room Light'
      # cloak_lamp:
      #   command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey3"
      #   command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey11"
      #   friendly_name: 'Cloak Lamp'
      # living_room_light:
      #   command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey4"
      #   command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey12"
      #   friendly_name: 'Living Room Light'
    #  cloak_xmas_lights:
    #    command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey6"
    #    command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey14"
    #    friendly_name: 'Cloak Xmas Lights'
    #  cloak_left_xmas_lights:
    #    command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey3"
    #    command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey11"
    #    friendly_name: 'Cloak Left Xmas Lights'
    #  kitchen_lamp:
    #    command_on: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey3"
    #    command_off: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey11"
    #    friendly_name: 'Kitchen Lamp'
    #  aquarium_light:
    #    command_on: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey4"
    #    command_off: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey12"
    #    friendly_name: 'Aquarium Light'
    #  living_room_xmas_tree:
    #    command_on: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey5"
    #    command_off: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey13"
    #    friendly_name: 'Living Room Xmas Tree'
      master_bedroom_light:
        command_on: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey7"
        command_off: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey15"
        friendly_name: 'Master Bedroom Light'
#      outside_xmas_lights:
#        command_on: "curl --silent -X GET http://192.168.0.152/cm?cmnd=RfKey1"
#        command_off: "curl --silent -X GET http://192.168.0.152/cm?cmnd=RfKey9"
#        friendly_name: 'Outside Xmas Lights'
#      external_lights:
#        command_on: 'curl -k "https://192.168.0.63/json.htm?type=command&param=switchlight&idx=4&switchcmd=On"'
#        command_off: 'curl -k "https://192.168.0.63/json.htm?type=command&param=switchlight&idx=4&switchcmd=Off"'
#        friendly_name: 'External Lights'
      ps4:
        command_on: "echo on"
        command_off: "echo off"
        command_state: "nc -z -w 5 192.168.0.207 9295"
        friendly_name: PS4

hive:
  username: !secret hive_user
  password: !secret hive_pass

konnected:
  api_host: !secret api_host
  access_token: !secret konnected_access_token
  devices:
    - id: '600194744429'
      binary_sensors:
        - zone: 2
          type: motion
          name: 'Spare 1'
        - zone: 3
          type: motion
          name: 'Garage'
        - zone: 4
          type: motion
          name: 'Hall'
        - zone: 5
          type: motion
          name: 'Kitchen'
        - zone: 6
          type: motion
          name: 'Living Room'
      switches:
        - zone: out
          name: 'Outside Garage Door'
          activation: low
          momentary: 500
    - id: 807d3a6ef50f
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Study'
          inverse: true
        - zone: 2
          type: motion
          name: 'Toy Room'
          inverse: true
        - zone: 3
          type: motion
          name: 'Office'
          inverse: true
        - zone: 4
          type: motion
          name: 'Landing'
          inverse: true
        - zone: 5
          type: motion
          name: 'Master Bedroom'
          inverse: true
        - zone: 6
          type: motion
          name: 'Lukes Room'
          inverse: true
      switches:
        - zone: out
          name: 'Beep Beep'
          momentary: 65
          pause: 55
          repeat: 4
        - zone: out
          name: 'Entry Exit Delay'
          momentary: 50
          pause: 1000
          repeat: 5
        - zone: out
          name: 'Chime'
          momentary: 200 
        - zone: out
          name: 'Siren'
    - id: bcddc2018e2e
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Spare 2'
    - id: 84f3ebb35cae
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Spare 3'

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.200-254
    consider_home: 180
  - platform: ping
    hosts:
      zak_pc:     192.168.0.20
      sonoff150:  192.168.0.150
      sonoff151:  192.168.0.151
      sonoff152:  192.168.0.152
      nas:        192.168.0.100
      izzy:       192.168.0.63
      aqua:       192.168.0.65
      virgin_router: 192.168.0.1
      asus_router:   192.168.0.3
      konnected1: 192.168.0.170
      konnected2: 192.168.0.171
      konnected3: 192.168.0.172
      konnected4: 192.168.0.173

weblink:
  entities:
    - name: Aqua Cam
      url:  http://127.0.0.1/
      icon: mdi:fish
    - name: Sonoff 150
      url:  http://192.168.0.150/
      icon: mdi:wifi
    - name: Sonoff 151
      url:  http://192.168.0.151/
      icon: mdi:wifi
    - name: Sonoff 152
      url:  http://192.168.0.152/
      icon: mdi:wifi
    - name: Konnected 1
      url:  http://192.168.0.170:15619/
      icon: mdi:wifi
    - name: Konnected 2
      url:  http://192.168.0.171:15271/
      icon: mdi:wifi
    - name: Konnected 3
      url:  http://192.168.0.172:8101/
      icon: mdi:wifi
    - name: Konnected 4
      url:  http://192.168.0.173:19754/
      icon: mdi:wifi

python_script:

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
