homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.395311
  longitude: -2.885974
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 52
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

recorder:
  db_url: !secret recorder_db_url

logger:
  default: info
  logs:
    homeassistant.components.sensor.hive: debug
    homeassistant.components.konnected: debug

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
#  api_password: !secret http_api_password
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Notifications
notify:
  - name: barry
    platform: command_line
    command: 'read input ; /usr/bin/curl -u o.nXQZM8hHjAaBOkcnLWuzn74JQNpz11wX: https://api.pushbullet.com/v2/pushes -d type=note -d title="Home Alert!" -d "body=${input}"'
  - name: ruth
    platform: pushbullet
    api_key: !secret pushbullet_api_ruth

panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://192.168.0.67:1880
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://192.168.0.67:8888/
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.0.67:3000

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state


alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: 1234
    pending_time: 5
    delay_time: 5
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

# Webcams
#camera:
#- platform: mjpeg
#  mjpeg_url: http://192.168.0.65/html/cam_pic_new.php?pDelay=400000
#  name: AquaCam
camera:
  - platform: generic
    name: Fish Cam
    still_image_url: http://192.168.0.65/html/cam_pic.php

ifttt:
  key: by3u5tQhR__RQFMYDypgzG

weather:
  - platform: darksky
    api_key: !secret darksky_api2

# Weather prediction
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
  - platform: worldclock
    name: New York
    time_zone: America/New_York
  - platform: yr
  - platform: command_line
    name: Aquarium Temperature
    command: "curl --silent -X GET http://192.168.0.65/html/28-041685bc33ff_temp.txt"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "째C"
  - platform: command_line
    name: Aquarium Temperature 2
    command: "curl --silent -X GET http://192.168.0.65/html/28-020291771148_temp.txt"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "째C"
  - platform: command_line
    name: Garage Temperature
    command: "curl --silent -X GET http://192.168.0.63/1-wire/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "째C"
  - platform: command_line
    name: Hot Water Temperature
    command: "curl --silent -X GET http://192.168.0.63/1-wire/temp2"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "째C"
  - platform: season
    type: astronomical
  - platform: uptime
  - platform: version

#  - platform: template
#    sensors:
#      playstation:
#        value_template: "{% if is_state('device_tracker.0cfe45d692b7', 'home') %}ON{% else %}OFF{% endif %}"
#        friendly_name: 'Playstation 4'
#      280dfc4c0320:
#        value_template: "{% if is_state('device_tracker.280dfc4c0320', 'home') %}ON{% else %}OFF{% endif %}"

  - platform: darksky
    api_key: !secret darksky_api3
    update_interval: '00:30'
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase

  - platform: history_stats
    name: PS4 today
    entity_id: switch.ps4
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'


  - platform: template
    sensors:
      ps4_today_time:
        value_template: '{{ states.sensor.ps4_today.attributes.value }}'

  - platform: template
    sensors:
       hall_temperature:
          friendly_name: "Hall Temperature"
          value_template: "{{  states.climate.heating.attributes.current_temperature }}"

  - platform: template
    sensors:
       hive_battery:
          friendly_name: "Hive Battery"
          value_template: "{{  states.climate.heating.attributes.battery_level }}"

  - platform: template
    sensors:
       hall_thermostat_temp_setting:
          friendly_name: "Hall Thermostat Temp Setting"
          value_template: "{{  states.climate.heating.attributes.temperature }}"

  - platform: template
    sensors:
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'

#  - platform: uk_transport
#    app_id: !secret uk_transport_appid
#    app_key: !secret uk_transport_appkey
#    queries:
#      - mode: train
#        origin: BGE
#        destination: LIV
#  - platform: template
#    sensors:
#      kitchen_state:
#        value_template: '{{ states("media_player.kitchen") }}'
#        friendly_name: 'Kitchen Chromecast'



# Text to speech
tts:
  - platform: google

# Cloud
cloud:

mqtt:
  password: !secret mqtt_api_password
  discovery: true
  discovery_prefix: sonoffs

switch:
  - platform: command_line
    switches:
      toy_room_light:
        command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey2"
        command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey10"
        friendly_name: 'Toy Room Light'
      living_room_light:
        command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey4"
        command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey12"
        friendly_name: 'Living Room Light'
      master_bedroom_light:
        command_on: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey7"
        command_off: "curl --silent -X GET http://192.168.0.150/cm?cmnd=RfKey15"
        friendly_name: 'Master Bedroom Light'
      aquarium_light:
        command_on: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey4"
        command_off: "curl --silent -X GET http://192.168.0.151/cm?cmnd=RfKey12"
        friendly_name: 'Aquarium Light'
      external_lights:
        command_on: 'curl -k "https://192.168.0.63/json.htm?type=command&param=switchlight&idx=4&switchcmd=On"'
        command_off: 'curl -k "https://192.168.0.63/json.htm?type=command&param=switchlight&idx=4&switchcmd=Off"'
        friendly_name: 'External Lights'
      ps4:
        command_on: "echo on"
        command_off: "echo off"
        command_state: "nc -z -w 5 192.168.0.207 9295"
        friendly_name: PS4

hive:
  username: !secret hive_user
  password: !secret hive_pass

konnected:
#  api_host: !secret api_host
  access_token: y0UBGvOWgj
  devices:
    - id: '600194744429'
      binary_sensors:
        - zone: 1
          type: door
          name: 'Garage Door Open'
        - zone: 2
          type: door
          name: 'Garage Door Closed'
        - zone: 3
          type: motion
          name: 'Garage'
        - zone: 4
          type: motion
          name: 'Hall'
        - zone: 5
          type: motion
          name: 'Kitchen'
        - zone: 6
          type: motion
          name: 'Living Room'
      switches:
        - zone: out
          name: 'Garage Door'
          activation: low
          momentary: 500
    - id: 807d3a6ef50f
      binary_sensors:
        - zone: 1
          type: motion
          name: 'Study'
        - zone: 2
          type: motion
          name: 'Toy Room'
        - zone: 3
          type: motion
          name: 'Office'
        - zone: 4
          type: motion
          name: 'Landing'
        - zone: 5
          type: motion
          name: 'Master Bedroom'
        - zone: 6
          type: motion
          name: 'Lukes Room'
      switches:
        - zone: out
          name: 'Beep Beep'
          momentary: 65
          pause: 55
          repeat: 4
        - zone: out
          name: 'Entry Exit Delay'
          momentary: 50
          pause: 1000
          repeat: 5
        - zone: out
          name: 'Chime'
          momentary: 200 

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.200-254
    home_interval: 60
  - platform: ping
    hosts:
      zak_pc: 192.168.0.20

weblink:
  entities:
    - name: Aqua Cam
      url:  http://127.0.0.1/
      icon: mdi:fish

python_script:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
