- id: '1539030610493'
  alias: 5 Min Game Warning
  trigger:
  - at: '19:55'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The time is 19:55, Luke & Zak, you have 5 minutes to finish your games
- alias: Game Over
  trigger:
  - at: '20:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The time is 8 Oclock, time to turn off all electronics.  The playstation
        has been on for {{states.sensor.ps4_today.state|round}} hours today.
  id: d0e63fa7400c498c857966da6d157931
- id: '1539075329069'
  alias: Playstation Time Limit
  trigger:
    platform: numeric_state
    entity_id: sensor.ps4_today
    value_template: '{{ states.sensor.ps4_today.state }}'
    above: 5
  condition:
    condition: time
    after: '19:00:00'
    before: '21:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.downstairs
      volume_level: 0.5
  - service: tts.google_say
    entity_id: media_player.downstairs
    data_template:
      message: The playstation has been on for more than 4 hours, please finish your
        game and turn it off.
